name: Dependabot automerge

on:
    - pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: write
    pull-requests: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        steps:
            - name: Enable auto-merge for Dependabot PRs
              run: gh pr comment "$PR_URL" --body "@dependabot merge"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
