name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: php-actions/composer@v6
        with:
          # Lowest supported PHP version
          php_version: "8.1"
          php_extensions: intl
      - run: composer run package
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: zip
          GHR_PATH: releases/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
